---
- name: Copy configuration file with variables
  hosts: all
  become: yes
  vars:
    app_name: "MyApp"
    app_version: "1.0.0"
  tasks:
    - name: Copy app config
      template:
        src: app_config.j2
        dest: /etc/myapp/config.conf
