---
- name: Loops Playbook
  hosts: all
  become: yes

  tasks:
    - name: Say Hello to All
      debug:
        msg: "Hello, {{ item }}!"
      loop:
        - "Vasya"
        - "Petya"
        - "Masha"
        - "Ilya"
