---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes

  vars:
    source_file: /home/ladmin/.ansible/index.html  # Путь к исходному файлу
    destin_file: /var/www/html

  tasks:
    - name: Check and Print LINUX Version
      debug: 
        var: ansible_os_family

    - name: Install Apache WebServer
      apt:
        name: apache2
        state: latest

    - name: Copy MyHomePage to Servers
      copy:
        src: "{{ source_file }}"
        dest: "{{ destin_file }}"
        mode: '0555'

    - name: Start Apache Server
      service:
        name: apache2
        state: started
        enabled: yes

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

