---
- name: My Super Puper Playbook for Variables Leson
  hosts: all
  become: yes


  vars: 
    message1: Privet
    message2: World
    secret:  123123123


  tasks:


  -  name: Print Server Variable
     debug:
       var: secret
  

  -  debug:
      msg: "Sekretnoe slovo {{secret}}"

  -  set_fact: full_message="{{message1}} {{message2}}"
  
  -  debug:
       var: full_message

  -  shell: uptime
     register: results

  -  debug:
      msg: "{{results.stdout}}"
